# fly.toml app configuration file generated for qred-project-frontend on 2024-11-25T13:50:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qred-project-frontend'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  API_DOMAIN_URL= 'https://qred-project-backend.fly.dev'
  WEB_DOMAIN_URL= 'https://qred-project-frontend.netlify.app'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
